owner: o-tr
repo: upptime

sites:
  - name: Weather API
    url: https://weather.ootr.jp/healthz
  - name: ImageSlide Converter
    url: https://slide.ootr.jp/api/healthz

status-website:
  cname: uptime.ootr.jp
  logoUrl: https://docs.ootr.jp/img/favicon.ico
  name: Upptime
  introTitle: 鮪技研が管理するサーバー上で稼働するサービスのUptime情報です
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
